### ISSUE TITLE
Batch Anime Mapping - Part 1

### ISSUE THREAD

**Issue by NADESHIKON** [Anime-Lists/anime-lists#167]
https://docs.google.com/spreadsheets/d/1jpqpldBtl7JWBSkkkMIYhy3MJV7JZFmyIoLBmXX_dFM/edit?usp=sharing

I have collected some unmapped anime from my program and manually went through them and mapped each one, please add these to the mappings.

**Comment by BrutuZ** [comment]
Boy that was **A LOT** of work 😅!!!
Took me 2 hours to:
1. Copy the spreadsheet
2. Sort it by link
3. Find/Replace to extract the TMDB IDs
4. Search each title on IMDB 🐢
5. Copy all TVDB links + Find/Replace to extract the season number
6. **Open each TVDB link**
    7. Click the series name link
    8. Double-check some with AniDB ([_Bakugan Armored Alliance_](https://docs.google.com/spreadsheets/d/1jpqpldBtl7JWBSkkkMIYhy3MJV7JZFmyIoLBmXX_dFM/edit#gid=2058339286&range=A4) doesn't seem to exist on TVDB yet for instance)
    9. Copy the TVDB ID
    10. Paste it back on the Spreadsheet
11. Finally use a formula to put it all together in the XML format to make it easier to copy and paste
12. Manually find each AniDB ID and paste from previous step

I don't mean to belittle the contribution in any way, but since you went through the work of cross-referencing the entries manually and are no stranger to git, this could've been a PR 😀

That beauty of a diff 9ed90b220b9d6a676e66be7d40b8e37fc381f175 could be yours! 🤣
