### ISSUE TITLE
Convention to mapping AniDB "Others" episodes?

### ISSUE THREAD

**Issue by cure1245** [Anime-Lists/anime-lists#47]
I'd like to take on fixing the mappings for Owarimonogatari season 2 (anidbid 13033). I notice that we have a very nice match between TVDB season 5 and the "Other" episodes on AniDB: specifically O2,O3, and O5-O9. Is there a convention within the XML for mapping these episodes? For example, I know Absolute Series Scanner uses 401-500 to map O001-O100 in Anidb. If there's a way to do that, I should be able to fix this.

**Comment by sven-7** [comment]
Right now, I don't believe this can do any mappings to "Other" on AniDB. Regular episodes get equated to Seasons and Specials are season "0". Other, as far as I know, has never been used. That being said, I can update the mapping for this as I believe it's wrong.

**Comment by reconman** [comment]
@sven-7 Your current mapping probably won't work at all. Assuming you're using AniDB metadata, Hama would load the data for the first TVDB episode and the rest would be ignored.

If you're using TVDB metadata for Monogatari instead, the title and summary for the first 4 episodes would be the same if AniDB data is preferred in your advanced settings.

I've noticed that Saiki K. has a mapping where 3 AniDB episodes are 1 TVDB episode and if you set AniDB titles to preferred, every episode will have (Part 1) in its title. In that case, it would be better to just not use any mapping.

And generally regarding O episodes: Plex doesn't even offer O-seasons so there is no way you can ever use them if you're using AniDB entries as base. You can only split or combine episodes using the `pt1, pt2` or `E01-02` Plex file syntax to map your episode files to the AniDB entries.

And I can guarantee that Hama can't deal with them either. That's why I don't want to support them.

**Comment by sven-7** [comment]
We can just revert them then. 

Regarding Saiki, one of the folks who used to work on the list did that. It's worked very well, from what I can tell. 

I really don't want to get into Other either. Overall, Monogatari is a mess and best just to do things manually.

**Comment by reconman** [comment]
Seems like there's an undocumented convention of T episodes being 201, 202, ... and O episodes being 401, 402, ...

There are some shows with that kind of mapping.

**Comment by reconman** [comment]
> For example, I know Absolute Series Scanner uses 401-500 to map O001-O100 in Anidb. If there's a way to do that, I should be able to fix this.

I somehow missed that part.

**Comment by reconman** [comment]
Fixed in 1ec96c709017fa200963acfebc9bd0c497862f59
