### ISSUE TITLE
Ani ni Tsukeru Kusuri wa Nai! 4

### ISSUE THREAD

**Issue by EndOfLine369** [Anime-Lists/anime-lists#58]
https://anidb.net/anime/15600

https://www.thetvdb.com/series/please-take-my-brother-away
TVDBID 327261
Season 4

**Comment by reconman** [comment]
We would appreciate it if you could open a pull request next time, that way we can merge it quickly. For example, I'm stuck at work now.

Reviewing changes takes 2 minutes, while doing the change myself is not a thing I can do right now because I don't commit to private repository during my work time.

**Comment by EndOfLine369** [comment]
Thanks @sven-7
@reconman, I'm in no rush. Use to the long wait from ScudLee. 😁

**Comment by sven-7** [comment]
You bet! As long as it's not a complicated request, I don't mind ;)
